### PR TITLE
Added module to config. Updated project to latest versions

### PR DESCRIPTION
**Pull request by jgmpzman**
This is a fix for: NullPointerException after updating IntelliJ #17

I ran into this issue myself and when I downloaded the code. It looks like if the configuration you enter for Deployment on the config is not the root directory of a module then looking up the module results in a null value. That causes a NullPointerException farther down the line. It seems like the user should be able to specify a Deployment Directory and the Module directory, so I added a config for the module. I also updated the gradle and intellij plugin imports to newer versions and verified on the latest intellij version 2019.1.1.

If you are interested in this PR, let me know and I will merge it in.

### CODE REVIEW

**Comment by yuezk** [comment]
Hi, @zengkid Are you plan to release a new version of this plugin, since it has been merged for a long time. A lot of users are waiting for this to fix the NPE exception. Thanks.

**Comment by zengkid** [comment]
Hi, Devin Yue

   Already release the new version.

Regards
Yi


________________________________
发件人: Kevin Yue <notifications@github.com>
发送时间: Friday, September 20, 2019 9:49:46 PM
收件人: zengkid/SmartTomcat <SmartTomcat@noreply.github.com>
抄送: zengkid <zengkid@msn.com>; Mention <mention@noreply.github.com>
主题: Re: [zengkid/SmartTomcat] Added module to config. Updated project to latest versions (#20)


Hi, @zengkid<https://github.com/zengkid> Are you plan to release a new version of this plugin, since it has been merged for a long time. A lot of users are waiting for this to fix the NPE exception. Thanks.

―

**Comment by yuezk** [comment]
@zengkid Have you uploaded it to the JetBrains plugin site? Seems that the last update time of this plugin is May 20, 2018. https://plugins.jetbrains.com/plugin/9492-smart-tomcat

**Comment by zengkid** [comment]
Hi, Kevin Yue

   The plugin update is pending JetBrains approval, please wait for few days.

Regards


________________________________
发件人: Kevin Yue <notifications@github.com>
发送时间: Sunday, September 22, 2019 9:32:30 PM
收件人: zengkid/SmartTomcat <SmartTomcat@noreply.github.com>
抄送: zengkid <zengkid@msn.com>; Mention <mention@noreply.github.com>
主题: Re: [zengkid/SmartTomcat] Added module to config. Updated project to latest versions (#20)


@zengkid<https://github.com/zengkid> Have you uploaded it to the JetBrains plugin site? Seems that the last update time of this plugin is May 20, 2018. https://plugins.jetbrains.com/plugin/9492-smart-tomcat

―

**Pull request merged**
